version: '3.8'

services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
      volumes:
        - .:/code
      ports:
        - '8000:8000'
      depends_on:
        - db
      env_file:
        - .env
      restart: always
      networks:
        - db_network

  db:
      image: postgres
      restart: always
      ports:
        - '5433:5432'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345678
        - POSTGRES_DB=manager_project

      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - db_network


networks:
  db_network:
    driver: bridge

volumes:
    pgdata: